### ISSUE TITLE
No link in admin

### ISSUE THREAD

**Issue by 0859170** [avra911/magento_fwcap#1]
There is no link appearing in the admin menu after installation, but I can reach the config page by manipulating the url.

**Comment by avra911** [comment]
You are right, I am thinking about moving it to one of the core's TAB
Thank you, i will let you know as soon as I have a fix!

Best,
R

**Comment by avra911** [comment]
I moved the menu to magento General Section to be accesible: https://github.com/avra911/magento_fwcap/commit/69f2ff68330aeff335fdb59d86f6000565a0ca9b

thanks again,
R

**Comment by 0859170** [comment]
Thanks :+1:
